### ISSUE TITLE
Generated code is vulnerable for Denial of Service (DoS)

### ISSUE THREAD

**Issue by mvanvendeloo** [7nohe/openapi-react-query-codegen#2]
The generated code contains a possible DoS vulnerability in request.ts:

```
const getUrl = (config: OpenAPIConfig, options: ApiRequestOptions): string => {
 const encoder = config.ENCODE_PATH \|\| encodeURI;

const path = options.url.replace('{api-version}', config.VERSION).replace(/{(.*?)}/g, (substring: string, group: string) => {
 if (options.path?.hasOwnProperty(group)) {
return encoder(String(options.path[group]));
}
 return substring;
 });
```
The risk is not great, since we can assume the URL is not user input. 
See: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS

**Comment by 7nohe** [comment]
@mvanvendeloo  Thanks for the issue!
Unfortunately, request.ts is fully dependent on [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen).
Therefore, it is better to create an Issue [there](https://github.com/ferdikoomen/openapi-typescript-codegen/issues).

FYI, there is also an option (`--client`) that allows you to choose an HTTP client such as `axios` or `node-fetch`, and I recommend using that until the issue is resolved.

See available HTTP clients [here](https://github.com/ferdikoomen/openapi-typescript-codegen#support).
